export const DELETE_ARTICLE = 'DELETE_ARTICLE'
export const SELECT_ARTICLES = 'SELECT_ARTICLES'
export const SET_DAY_RANGE = 'SET_DAY_RANGE'
export const RESET_DAYS = 'RESET_DAYS'
export const ADD_COMMENT = 'ADD_COMMENT'
export const LOAD_ALL_ARTICLES = 'LOAD_ALL_ARTICLES'

export const START = '_START'
export const SUCCESS = '_SUCCESS'
export const FAIL = '_FAIL'